services:
  - type: web
    name: iot-backend
    env: node
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MQTT_BROKER_HOST
        value: test.mosquitto.org
      - key: MQTT_BROKER_PORT
        value: 8080
      - key: MQTT_PROTOCOL
        value: ws
      - key: MQTT_USERNAME
        value: ''
      - key: MQTT_PASSWORD
        value: '' 